services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Maispace\Translate\:
    resource: '../Classes/*'

  Maispace\Translate\Controller\TranslateController:
    public: true

  Maispace\Translate\EventListener\TranslateButtonEventListener:
    tags:
      - name: event.listener
        identifier: 'maispace-translate/modify-button-bar'
        event: TYPO3\CMS\Backend\Template\Components\ModifyButtonBarEvent
