name: CI

on:
  push:
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    strategy:
      matrix:
        php: ['8.4', '8.5']
      fail-fast: false
    uses: mai-space-de/www.bgm-pulheim.org/.github/workflows/extension-ci.yml@main
    with:
      php-version: ${{ matrix.php }}
